name: Test

on:
  push:
    branches: [main]
    paths:
      - "scripts/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
  pull_request:
    paths:
      - "scripts/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest -v
